# Site settings
title: SerreÉTS
email: none@none
url: https://example.github.io
description: "Site officiel du club SerreÉTS."
tagline: "Génie alternatif"
logoPath: "img/logo_small.png"
favIconPath: "img/favicon.png"
commanditeEtsPath: "img/ets_logo_footer.png"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
# Version possible pour la couleur secondaire: 54201C
color:
  primary: 9DB27A #80B3FF
  secondary: 635147 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Club SerreÉTS
  location: École de Technologie Supérieure
  social: Ailleurs sur le web
  credits: Commanditaires

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://www.facebook.com/SerreETS
  - title: github
    url: http://github.com/SerreETS

# Postal address (add as many lines as necessary)
address: 
  - line: 1100 Rue Notre-Dame Ouest
  - line: Montréal, QC H3C 1K3, Canada
  - line: Local A-1172

# Credits content
#credits: 

# Build settings
markdown: kramdown
permalink: pretty
